#!/bin/bash

options=(
	style=round
	width=10.0
	hidpi=on
	active_color=0xfff72585
	inactive_color=0xff414550
)

borders "${options[@]}"


# brew tap FelixKratz/formulae
# brew install borders
# Higher to sonoma apple version!
# borders active_color=0xff80ed99 inactive_color=0xff494d64 width=8.0
# borders active_color=0xff06d6a0 inactive_color=0xff494d64 width=8.0 # GREEN
# borders active_color=0xffe5383b inactive_color=0xff494d64 width=8.0 # RED
# borders active_color=0xffffb627 inactive_color=0xff494d64 width=8.0 # YELLOW
# borders active_color=0xff5c0099 inactive_color=0xff494d64 width=8.0 # DARK PURPLE
# borders active_color=0xfff72585 inactive_color=0xff494d64 width=10.0 # PINK